import { Toaster } from '@/components/ui/toaster';
import ProviderQuery from '@/providers/provider-query';
import SessionAuthProvider from '@/providers/session-auth-provider';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionAuthProvider>
          <ProviderQuery>
            <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
              {children}
            </ThemeProvider>
            <Toaster />
          </ProviderQuery>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
